const fs = require('fs');
const data = JSON.parse(fs.readFileSync('public/miracles.json', 'utf8'));
function updateMiracle(id, updates) {
  const miracle = data.find(m => m.id === id);
  if (miracle) { Object.assign(miracle, updates); return true; }
  return false;
}

updateMiracle('miracle-97', {
  fullDescription: `In the year 1010, in the small Catalan village of Ivorra, a parish priest named Father Bernat Oliver was silently tormented by doubts about the Real Presence of Jesus Christ in the Eucharist — a crisis of faith that mirrored a broader theological conflict spreading across medieval Europe. The heretical doctrines of Berengar of Tours, which denied Transubstantiation, had begun to unsettle clergy and faithful alike throughout the continent, and Bernat Oliver was not immune to this spiritual struggle.

One day during the celebration of Mass, at the very moment of Consecration, Father Oliver's doubt was answered with unmistakable clarity: the wine in the chalice was converted entirely into living Blood. The Blood did not remain contained — it poured over the rim of the chalice, onto the altar cloth, and flowed down to the ground. The event was witnessed by those present at the Mass and left the linen corporal permanently stained with what the Church would come to authenticate as miraculous Blood.

News of the event was brought immediately to Bishop Saint Ermengol of Urgell, who traveled to Ivorra in person to investigate and confirm the facts. Saint Ermengol then reported the miracle directly to Pope Sergius IV in Rome. The Pope issued a Pontifical Bull certifying that a true miracle had occurred. The relics — including the Blood-stained altar cloth — and the pontifical document were placed beneath the high altar of the parish church of Ivorra, dedicated to San Cugat, which was solemnly inaugurated in 1055.

Devotion to the miracle grew steadily over the centuries. A gothic reliquary dated to 1426 was crafted to house the sacred relics, including the blood-stained corporal and other relics entrusted by Pope Sergius IV to Saint Ermengol. By 1663, the volume of pilgrims visiting Ivorra each year necessitated the construction of a larger sanctuary. To this day, on the second Sunday of Easter, the people of Ivorra celebrate a solemn feast known as "la Santa Duda" — the Holy Doubt — in perpetual memory of the priest's faltering faith and the miracle that answered it.`,
  scientificEvidence: [
    "The Blood-stained altar cloth (corporal) has been continuously preserved since 1010 and remains visibly marked with the miraculous Blood, authenticated through multiple Church investigations over more than a millennium.",
    "Pope Sergius IV issued a formal Pontifical Bull following the investigation led by Bishop Saint Ermengol of Urgell, constituting the earliest known official ecclesiastical authentication of this miracle and confirming its genuineness through papal authority.",
    "The relics were enshrined in a gothic reliquary crafted in 1426, and the physical preservation of the cloth stained with Blood across more than ten centuries — without artificial preservation — has been cited as a sign of supernatural origin."
  ],
  witnessTestimonies: [
    { name: "Father Bernat Oliver", role: "Parish Priest of Ivorra", testimony: "The very priest whose doubt prompted the miracle. Father Oliver witnessed the wine in the chalice transform into living Blood before his eyes during the Mass, with the Blood flowing over the altar cloth and onto the ground — an event that permanently resolved his crisis of faith." },
    { name: "Saint Ermengol (Ermengaudus)", role: "Bishop of Urgell", testimony: "Traveled personally to Ivorra to investigate the reported miracle and confirmed its authenticity firsthand. He subsequently brought the details to Rome and presented the case before Pope Sergius IV, whose Pontifical Bull validated the miracle on the Bishop's testimony." },
    { name: "Pope Sergius IV", role: "Pope, Bishop of Rome (1009–1012)", testimony: "Upon receiving the report from Bishop Saint Ermengol, Pope Sergius IV issued a Pontifical Bull formally certifying the miracle of Ivorra as authentic, providing the highest level of ecclesiastical confirmation available." }
  ],
  historicalContext: "The Eucharistic miracle of Ivorra occurred in 1010, during a period of intense theological controversy in the Western Church. The teachings of Berengar of Tours (c. 999–1088), which questioned the doctrine of Transubstantiation and denied the Real Presence of Christ in the Eucharist, were beginning to spread and would cause significant doctrinal conflict throughout the 11th century. Ivorra was a small parish in the County of Urgell in medieval Catalonia, a region on the Christian frontier of the Iberian Peninsula during the Reconquista. The miracle's authentication by Pope Sergius IV helped reinforce orthodox Eucharistic teaching at a critical moment in Church history.",
  timeline: [
    { date: "1010", event: "During Mass, Father Bernat Oliver's doubts are answered when the wine transforms into living Blood, which flows over the altar cloth and onto the floor." },
    { date: "1010–1012", event: "Bishop Saint Ermengol of Urgell personally investigates the miracle and brings a report to Pope Sergius IV in Rome." },
    { date: "c. 1012", event: "Pope Sergius IV issues a Pontifical Bull certifying the miracle as authentic." },
    { date: "1055", event: "The parish church of Ivorra is inaugurated; the blood-stained corporal and Pontifical Bull are placed beneath the high altar." },
    { date: "1426", event: "A gothic reliquary is crafted to house the sacred relics." },
    { date: "1663", event: "A new, larger sanctuary is constructed at Ivorra to accommodate growing pilgrim numbers." },
    { date: "Annual", event: "The feast of 'la Santa Duda' (the Holy Doubt) is celebrated in Ivorra on the second Sunday of Easter." }
  ]
});

updateMiracle('miracle-98', {
  fullDescription: `In the town of Moncada, near Valencia, a priest named Mosén Jaime Carrós was consumed by a profound spiritual crisis. He had been ordained by a bishop appointed under the authority of the antipope Clement VII — the French claimant to the papacy who had been elected by dissident cardinals hoping to return the Holy See to Avignon. The resulting Western Schism (1378–1417) threw the entire Church into confusion, and Mosén Carrós feared that his ordination was invalid, that his Masses were null, and that the Hosts he distributed to the faithful were unconsecrated. He implored God for a clear sign.

On Christmas Day, 1392, an aristocratic woman named Angela Alpicat attended Mass at Moncada with her five-year-old daughter, Inés — the child who would later be venerated as the Blessed Inés de Moncada. At the conclusion of the Mass, the little girl refused to leave the church. When her mother pressed her for a reason, Inés said she wished to stay and play with the beautiful baby that the pastor had held in his hands during the Mass. Her mother was astonished: no such child was visible to the adult congregation.

The following day, the priest devised a careful test to verify the child's extraordinary perception. During Mass, he consecrated only one of two hosts and then approached little Inés. When he raised the consecrated host and asked what she saw, she replied, "I see Baby Jesus." He then raised the unconsecrated host and asked the same question. Inés answered simply, "I see a little white disc." The distinction was absolute and unmistakable. The congregation, having witnessed the test, erupted in joy. The validity of Mosén Carrós's ordination — and thus every Mass he had ever celebrated — had been miraculously confirmed through the pure eyes of a child. The event was documented in the Anales Eclesiasticos by ecclesiastical historian Fr. Odorico Raynaldi and is preserved in numerous documents in the archives of the city of Moncada.`,
  scientificEvidence: [
    "The miracle was formally documented by ecclesiastical historian Fr. Odorico Raynaldi in the Anales Eclesiasticos, providing a contemporaneous written record that underwent independent scholarly examination.",
    "The two-host test administered by Mosén Jaime Carrós constituted a controlled verification: when the consecrated host was elevated, the child identified 'Baby Jesus'; when the unconsecrated host was shown, she identified only 'a little white disc' — a distinction she could not have made naturally given her age.",
    "Multiple documents corroborating the event are preserved in the municipal archives of Moncada, providing layered historical attestation independent of purely ecclesiastical sources."
  ],
  witnessTestimonies: [
    { name: "Inés Alpicat (Blessed Inés de Moncada)", role: "Five-year-old daughter of Angela Alpicat; future Dominican nun", testimony: "After Christmas Mass, Inés refused to leave the church, telling her mother she wanted to stay with the beautiful baby the priest had been holding. The following day, during the verification test, she clearly distinguished between the consecrated host ('I see Baby Jesus') and the unconsecrated host ('I see a little white disc')." },
    { name: "Angela Alpicat", role: "Noblewoman of Moncada, mother of Inés", testimony: "Witnessed her daughter's refusal to leave the church after Christmas Mass and heard Inés describe seeing a beautiful child in the priest's hands — a vision unseen by Angela herself. She was present for the verification test and witnessed her daughter's accurate identification of the two hosts." },
    { name: "Mosén Jaime Carrós", role: "Parish priest of Moncada", testimony: "Tormented by doubts over the validity of his ordination due to the Western Schism, Mosén Carrós heard of Inés's vision and designed the verification test. He elevated the consecrated then unconsecrated host before the child, receiving responses that he and the assembled congregation recognized as miraculous confirmation of his valid priesthood." }
  ],
  historicalContext: "The Eucharistic miracle of Moncada unfolded against the turbulent backdrop of the Western Schism (1378–1417), one of the most destabilizing crises in medieval Church history. Following the disputed election of Pope Urban VI in 1378, a faction of French cardinals elected an antipope, Clement VII, and established a rival court at Avignon. Clergy ordained under bishops of the antipope's line were left in agonizing uncertainty about their sacramental ministry. Moncada, near Valencia in the Crown of Aragon, was in a region where the schism created particular pastoral distress. The miracle directly confirmed that the sacramental intention of the Church transcended political divisions.",
  timeline: [
    { date: "1378", event: "The Western Schism begins when dissident cardinals elect the antipope Clement VII, creating a rival papal court at Avignon." },
    { date: "c. 1390–1392", event: "Mosén Jaime Carrós, ordained under the antipope's line, begins doubting the validity of his priesthood and prays urgently for a divine sign." },
    { date: "December 25, 1392", event: "On Christmas Day, Angela Alpicat and her five-year-old daughter Inés attend Mass. After Mass, Inés refuses to leave, saying she wants to stay with the beautiful baby the priest held during Mass." },
    { date: "December 26, 1392", event: "Mosén Carrós devises a verification test, consecrating only one of two hosts. Inés clearly identifies 'Baby Jesus' for the consecrated host and 'a little white disc' for the unconsecrated one." },
    { date: "Post-1392", event: "The miracle is recorded by Fr. Odorico Raynaldi in the Anales Eclesiasticos and documented in the municipal archives of Moncada." },
    { date: "Post-1392", event: "Inés Alpicat enters religious life, joins the Dominican order, and is later beatified as Blessed Inés de Moncada." }
  ]
});

updateMiracle('miracle-99', {
  fullDescription: `In the year 1657, two senior Benedictine prelates — the Most Reverend Father Don Bernardo de Ontevieros, General of the Benedictine Order in Spain, and Abbot Don Millán de Mirando — arrived at the famed Monastery of Our Lady of Montserrat in Catalonia. During their stay, a woman arrived at the monastery with her young daughter to seek a spiritual favor. The girl earnestly implored Abbot Millán de Mirando to offer three Masses for the soul of her recently deceased father, whom she was convinced was enduring the pains of purgatory. The abbot, moved by the child's faith and devotion, agreed.

The following day, the abbot celebrated the first Mass of Requiem on behalf of the girl's father. During the Mass, the young girl knelt in prayer before the altar and suddenly perceived a vision invisible to those around her: her father, kneeling at the bottom step of the main altar, surrounded by terrifying flames. When the priest was informed, he instructed her to mark the exact spot where her father appeared by placing a piece of linen tissue on the ground. She did so — and the tissue immediately burst into flames before the eyes of everyone present in the church, though none of the other witnesses could see the girl's father. The burned tissue became the first tangible, physical evidence of the miraculous phenomenon.

At the second Mass, celebrated for the same intention, the girl again saw her father — this time he had risen a step higher, standing beside the deacon, and was dressed in a vividly colored garment rather than the flames of the first apparition. His spiritual condition was visibly improving with each sacrifice of the Mass. At the conclusion of the third and final Mass, the girl cried out in joy: the father appeared now in a radiant snow-white garment, and as the Mass ended, she exclaimed to all present, "There is my father going away and rising into the sky!" The soul of the deceased had passed from purgatory into the glory of heaven, visibly accompanied by the graces of the Holy Sacrifice.`,
  scientificEvidence: [
    "A piece of linen tissue placed by the girl at the location of her father's apparition during the first Mass spontaneously ignited and burned in full view of the assembled congregation — a physical phenomenon witnessed by high-ranking Church officials, clergy, and lay people, for which no natural explanation was identified.",
    "The burned tissue was preserved as a relic and physical corroboration of the event, providing a tangible artifact whose anomalous combustion during the Mass was attested to by multiple independent witnesses of high social and ecclesiastical standing.",
    "The sequential progression of the father's appearance across three Masses — from flames to colored garments to radiant white — was consistent across all three liturgical events and corresponded to no external suggestion or prompting from the adults present."
  ],
  witnessTestimonies: [
    { name: "The Young Daughter", role: "Visionary; daughter of the deceased man", testimony: "During the first Mass, she saw her father kneeling at the altar steps surrounded by flames, then directed others to place tissue on the spot — which caught fire. During the second Mass she saw him beside the deacon in colored vestments. At the end of the third Mass she exclaimed, 'There is my father going away and rising into the sky!'" },
    { name: "Don Bernardo de Ontevieros", role: "Most Reverend General of the Benedictine Order in Spain", testimony: "Personally present during all three Masses at Montserrat, witnessed the tissue burst into flames when placed by the girl at the site of the apparition, and attested to the supernatural nature of the events as the highest-ranking Benedictine prelate in Spain." },
    { name: "Abbot Don Millán de Mirando", role: "Abbot of Montserrat; celebrant of the three Masses", testimony: "Agreed to celebrate three Masses at the girl's request, was informed of the vision during the first Mass, instructed the girl to mark the spot with tissue, and directly witnessed the tissue's spontaneous combustion at the altar steps." }
  ],
  historicalContext: "The Eucharistic miracle of Montserrat occurred in 1657, at one of the most spiritually significant Benedictine monasteries in Europe. The Monastery of Our Lady of Montserrat, founded in the 9th century on the dramatic rocky mountain of Montserrat in Catalonia, was a major pilgrimage destination and center of Marian and Eucharistic devotion. The 17th century was a period of intense focus on Purgatory and the theology of suffrages within the Catholic Church, partly as a response to the Protestant Reformation's rejection of prayers for the dead. The Council of Trent (1545–1563) had recently reaffirmed Catholic teaching on both Purgatory and the propitiatory value of the Mass for the living and the dead.",
  timeline: [
    { date: "1657", event: "Don Bernardo de Ontevieros and Abbot Don Millán de Mirando arrive at the Monastery of Montserrat for a visitation." },
    { date: "1657", event: "A woman and her young daughter seek an audience with the Abbot; the girl begs him to celebrate three Masses for her deceased father's soul. The Abbot agrees." },
    { date: "First Mass, 1657", event: "During the first Requiem Mass, the girl sees her father surrounded by flames at the altar steps. When tissue is placed at the spot, it immediately ignites before all present." },
    { date: "Second Mass, 1657", event: "The girl again sees her father, now risen to stand beside the deacon in brightly colored garments — the flames have gone." },
    { date: "Third Mass, 1657", event: "At the conclusion of the third Mass, the father appears in a radiant snow-white garment. The girl cries out: 'There is my father going away and rising into the sky!'" },
    { date: "Post-1657", event: "The burned tissue is preserved as a relic; the event is recorded in the monastery's records as testimony to the efficacy of the Mass for souls in purgatory." }
  ]
});

updateMiracle('miracle-101', {
  fullDescription: `In the town of Onil, in the province of Alicante in the Valencia region of Spain, a sacrilegious theft of grave consequence took place on the night of November 5, 1824. A man named Nicolás Bernabeu — a former altar boy of the parish church of Saint James the Apostle — broke into the church and stole the monstrance containing the Blessed Sacrament, along with other religious valuables. His motive was purely financial: he intended to sell the precious objects for their material value.

In attempting to sell the stolen silver monstrance in the city of Alicante, Bernabeu aroused the suspicion of a shopkeeper who alerted the authorities. The thief was arrested, but before his capture he had already hidden the stolen goods — including the monstrance with the consecrated Host still enclosed within it — in a vegetable field in an area outside of town known as La Pedrera. Bernabeu thus left the Blessed Sacrament abandoned in a field, exposed to the elements for more than three weeks.

On November 28, 1824, a woman named Teresa Carbonell from the nearby town of Tibi was passing through the area of La Pedrera when she discovered the monstrance lying in the middle of the vegetable field. Remarkably, the consecrated Host inside was found to be perfectly intact — completely unaffected by the weeks of exposure to outdoor conditions, soil, and weather. The Host was returned to the parish church with a solemn procession of thanksgiving. What followed over the ensuing decades would become the enduring wonder of Onil: the consecrated Host did not consume or decay. On November 28, 1943 — exactly 119 years after Teresa Carbonell's discovery — Don Guillermo Hijarrubia, the delegate of the Archbishop of Valencia, conducted a formal ecclesiastical investigation and confirmed the authenticity of the miracle. To this day, the Host remains intact and is venerated each year in the parish church of Saint James the Apostle during the annual feast of "El Senyor Robat" — the Stolen Lord.`,
  scientificEvidence: [
    "On November 28, 1943 — exactly 119 years after the discovery of the stolen Host — Don Guillermo Hijarrubia, delegate of the Archbishop of Valencia, conducted a formal ecclesiastical investigation and officially confirmed the complete preservation of the Host, declaring the miracle authentic.",
    "The consecrated Host survived more than three weeks of outdoor exposure in a vegetable field in November without decomposition or damage — a physical anomaly given that unconsecrated bread of the same composition would deteriorate rapidly under such conditions of moisture, temperature variation, and soil contact.",
    "Continuous preservation of the Host for over 200 years since 1824, without artificial means of conservation, has been observed and documented through successive ecclesiastical inspections, and the Host remains on display in the parish church of Saint James the Apostle in Onil."
  ],
  witnessTestimonies: [
    { name: "Teresa Carbonell", role: "Woman from the town of Tibi", testimony: "On November 28, 1824, while passing through the field of La Pedrera near Onil, Teresa Carbonell discovered the stolen monstrance lying amid the vegetable rows. She found the consecrated Host within it completely intact despite more than three weeks of outdoor exposure. She reported the discovery, enabling the return of the Blessed Sacrament to the parish church." },
    { name: "Nicolás Bernabeu", role: "Former altar boy; perpetrator of the theft", testimony: "Bernabeu stole the monstrance containing the Blessed Sacrament on November 5, 1824. Attempting to sell the silver in Alicante, he was arrested after arousing suspicion; before his arrest he had abandoned the monstrance with the Host in the field of La Pedrera. His arrest provided the full account of the theft and the Host's location." },
    { name: "Don Guillermo Hijarrubia", role: "Delegate of the Archbishop of Valencia", testimony: "On November 28, 1943, exactly 119 years after the Host was found, Don Guillermo Hijarrubia conducted the official ecclesiastical investigation into the miracle. He confirmed the complete and inexplicable preservation of the Host and authenticated the miracle on behalf of the Archdiocese of Valencia." }
  ],
  historicalContext: "The miracle of Onil occurred in 1824, during a period of severe political and religious turbulence in Spain. The Peninsular War (1808–1814) against Napoleonic occupation had devastated Spanish society and weakened the Church's institutional structures. The subsequent struggle between liberal constitutionalists and absolutist royalists created an atmosphere of social disorder and anti-clerical sentiment. Sacrilegious thefts from churches were not uncommon in this period. The fact that a former altar boy committed the theft made the desecration particularly painful to the community of Onil. Against this backdrop of social upheaval and religious desecration, the miraculous preservation of the Host was experienced by the faithful as a sign of divine protection and the indestructibility of the Real Presence.",
  timeline: [
    { date: "November 5, 1824", event: "Nicolás Bernabeu breaks into the parish church of Saint James the Apostle in Onil and steals the monstrance containing the consecrated Host, along with other religious valuables." },
    { date: "November 5–28, 1824", event: "Bernabeu attempts to sell the stolen monstrance in Alicante; he is arrested after arousing suspicion. Before arrest, he abandons the monstrance with the Host in a vegetable field at La Pedrera." },
    { date: "November 28, 1824", event: "Teresa Carbonell of Tibi discovers the monstrance in the field of La Pedrera. The consecrated Host inside is found perfectly intact after more than three weeks of outdoor exposure. It is returned to the parish with a solemn procession." },
    { date: "1824 onward", event: "The Host remains intact and is enshrined in the parish church; the annual feast of 'El Senyor Robat' (The Stolen Lord) is established." },
    { date: "November 28, 1943", event: "Exactly 119 years after the discovery, Don Guillermo Hijarrubia formally investigates and authenticates the miracle, confirming the complete preservation of the Host." },
    { date: "Present", event: "The Host stolen in 1824 continues to be venerated in the parish church of Saint James the Apostle in Onil, remaining visibly intact after more than 200 years." }
  ]
});

updateMiracle('miracle-102', {
  fullDescription: `In the town of Ponferrada in the Kingdom of León (present-day Castile and León, Spain), the year 1533 brought both a sacrilegious crime and a series of supernatural signs that converged to prevent the desecration of the Blessed Sacrament. A parishioner named Juan de Benavente, driven by greed, resolved to steal from his own parish church. He took the tabernacle containing a precious silver ciborium filled with numerous consecrated Hosts and removed it from the church under cover of darkness. His intention was to sell the silver vessel for profit and discard the sacred contents.

Rather than carrying the tabernacle far, Juan de Benavente threw it into a dense blackberry thicket in a field the townspeople called the Arenal. He then attempted to find a buyer for the silver ciborium, but found himself increasingly anxious and unable to act — he could not sell the distinctive sacred vessel without arousing suspicion. Meanwhile, in the days and nights that followed, the residents of Ponferrada began to notice inexplicable phenomena near the Arenal: at night, brilliant flashes of light erupted from the blackberry patch, and during the day, a group of pure white doves hovered persistently over the same spot. Several crossbowmen tried to shoot the doves but found themselves unable to hit the birds — each attempt failed inexplicably.

The mysterious doves attracted the attention of a local miller named Nogaledo, who ventured directly into the thorny blackberry patch to investigate. Pressing through the briars, Nogaledo discovered the tabernacle, the silver ciborium, and the consecrated Hosts lying within the thicket, from which the intense lights had been emanating. He carefully retrieved the sacred objects and carried them to the parish church, whose bells — by another miraculous sign — had already begun ringing of their own accord, as if to announce the return of the Blessed Sacrament. A solemn procession was organized to receive the Hosts back into the church. Overcome with remorse, Juan de Benavente confessed his crime before the community. In memory of the miracle, a chapel was immediately erected on the site of the Arenal, and in 1570 an annual solemn procession on the eighth day after Corpus Christi was formally instituted.`,
  scientificEvidence: [
    "Multiple independent eyewitnesses from the town of Ponferrada reported seeing brilliant flashes of light emanating from the blackberry thicket at night over successive days — lights that had no identified natural source and whose location precisely corresponded to the hidden tabernacle later discovered by the miller Nogaledo.",
    "A group of crossbowmen made repeated attempts to shoot the white doves hovering over the Arenal field and were entirely unable to hit them — a failure deemed inexplicable given their skill, and interpreted as a supernatural protection of the site where the Hosts were hidden.",
    "The consecrated Hosts were found fully intact within the tabernacle after an extended period of outdoor exposure in a blackberry thicket, with no evidence of the deterioration that would be expected in natural circumstances — a preservation corroborated by the miller Nogaledo and the assembled congregation."
  ],
  witnessTestimonies: [
    { name: "Nogaledo", role: "Miller of Ponferrada; discoverer of the hidden tabernacle", testimony: "Intrigued by the white doves that persistently hovered over the Arenal blackberry patch despite repeated attempts by crossbowmen to drive them away, Nogaledo entered the thicket by hand to investigate. He discovered the tabernacle, silver ciborium, and consecrated Hosts within the briars — the source of the lights visible each night. He carried the sacred objects back to the parish church as the bells began to ring." },
    { name: "Townspeople of Ponferrada", role: "Residents who witnessed the nocturnal lights and the doves", testimony: "On successive nights following the theft, residents of Ponferrada observed unexplained flashes of light coming from the Arenal field. During the day, a group of white doves was seen hovering over the same location. Multiple crossbowmen attempted to shoot the doves and failed on each attempt." },
    { name: "Juan de Benavente", role: "Thief and parishioner; perpetrator of the sacrilege", testimony: "Overcome by remorse following the recovery of the Hosts and the miraculous signs that had accompanied their concealment, Juan de Benavente came forward and confessed his guilt before the entire community of Ponferrada, providing the full account of the theft." }
  ],
  historicalContext: "The miracle of Ponferrada took place in 1533, in the early decades of the Protestant Reformation. Martin Luther had posted his Ninety-Five Theses in 1517, and by 1533 the theological upheaval over the Eucharist — with Protestant reformers rejecting the Real Presence and the sacrificial nature of the Mass — was at its most acute. Spain under Emperor Charles V remained a staunchly Catholic kingdom. Ponferrada, situated in the Kingdom of León along the Camino de Santiago pilgrimage route, was a town with deep medieval Catholic roots. The theft and miraculous recovery of the consecrated Hosts resonated powerfully as a divine vindication of Catholic belief in the Real Presence at the very moment it was under attack from Protestant theology.",
  timeline: [
    { date: "1533", event: "Juan de Benavente steals the tabernacle containing a silver ciborium and numerous consecrated Hosts from his parish church in Ponferrada, intending to sell the precious metal." },
    { date: "1533", event: "Unable to sell the distinctive sacred vessel without suspicion, Benavente throws the tabernacle into a blackberry thicket in a field called the Arenal on the outskirts of Ponferrada." },
    { date: "1533 (nights following theft)", event: "Residents of Ponferrada observe brilliant flashes of light emanating from the Arenal blackberry patch each night. During the day, white doves hover persistently over the same spot." },
    { date: "1533", event: "Multiple crossbowmen attempt to shoot the doves hovering over the Arenal and fail inexplicably on every attempt, drawing increased attention to the location." },
    { date: "1533", event: "The miller Nogaledo ventures into the blackberry thicket and discovers the tabernacle, silver ciborium, and consecrated Hosts. He carries them to the parish church as the church bells ring spontaneously. Juan de Benavente then confesses his crime before the community." },
    { date: "1533", event: "A chapel is immediately built on the site of the Arenal where the Hosts were hidden." },
    { date: "1570", event: "The parish priest formally institutes an annual solemn procession on the eighth day of Corpus Christi to commemorate the miracle." }
  ]
});

console.log('✓ Spain Batch 3: Added 5 miracles (Ivorra/miracle-97, Moncada/miracle-98, Montserrat/miracle-99, Onil/miracle-101, Ponferrada/miracle-102)');
fs.writeFileSync('public/miracles.json', JSON.stringify(data, null, 2));
